version: "3"
services:
  laravel:
    container_name: ipublic-laravel
    build:
      context: ./
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    environment:
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_KEY=base64:OCNa/PJs+ugDBMUl+oXTY0EyxuKMosoO0WXFeEyfPw4="
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=ipublic"
      - "DB_USERNAME=ipublic"
      - "DB_PASSWORD=ipublic"
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=9000"
      ]
  db:
    container_name: ipublic-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=ipublic"
      - "MYSQL_USER=ipublic"
      - "MYSQL_PASSWORD=ipublic"
      - "MYSQL_ROOT_PASSWORD=ipublic"
